import { flushAllNotes } from "@/features/life/note-save-queue";
import { invoke } from "@tauri-apps/api/core";
import { useAuthStore } from "@/stores/auth-store";
import type { AccountRecord, CategoryRecord, DashboardData, TransactionRecord } from "@/types/finance";

const isTauri = () => typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
const key = (name: string) => `myfinance:${name}`;
const read = <T>(name: string, fallback: T): T => { try { const value = localStorage.getItem(key(name)); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };
const write = <T>(name: string, value: T) => localStorage.setItem(key(name), JSON.stringify(value));
const id = () => crypto.randomUUID();

export function toMinorUnit(value: string): number { const normalized = value.replace(/[^0-9.-]/g, ""); const parsed = Number(normalized); return Number.isFinite(parsed) ? Math.round(parsed * 100) : 0; }
export function fromMinorUnit(value: number): number { return value / 100; }

interface AccountDto { id: string; name: string; institution: string; type: string; currency: string; initialBalance: number; balance: number; isActive: boolean }
interface TransactionDto { id: string; type: string; accountId: string; accountName: string; categoryId?: string; categoryName?: string; amount: number; currency: string; merchant: string; transactionDate: number; note: string }
const mapAccount = (row: AccountDto): AccountRecord => ({ ...row, type: row.type as AccountRecord["type"], initialBalance: fromMinorUnit(row.initialBalance), balance: fromMinorUnit(row.balance), color: "#5b6ee1", symbol: row.name.slice(0, 1) });
const mapTransaction = (row: TransactionDto): TransactionRecord => ({ id: row.id, title: row.merchant || row.categoryName || "交易", account: row.accountName, category: row.categoryName || "未分类", amount: fromMinorUnit(row.amount), type: row.type === "INCOME" ? "income" : row.type === "EXPENSE" ? "expense" : "adjustment", timestamp: new Date(row.transactionDate).toLocaleString("zh-CN"), icon: "•", accountId: row.accountId, categoryId: row.categoryId, currency: row.currency, merchant: row.merchant, note: row.note, transactionDate: row.transactionDate });

export async function getAccounts(): Promise<AccountRecord[]> {
  if (isTauri()) { const rows = await invoke<AccountDto[]>("get_accounts"); return rows.map(mapAccount); }
  return read<AccountRecord[]>("accounts", []);
}
export async function saveAccount(input: { name: string; institution: string; type: string; currency: string; initialBalance: number }, accountId?: string): Promise<AccountRecord> {
  if (isTauri()) return mapAccount(await invoke<AccountDto>("save_account", { input, idOpt: accountId }));
  const accounts = read<AccountRecord[]>("accounts", []); const record: AccountRecord = { id: accountId ?? id(), name: input.name, institution: input.institution, type: input.type as AccountRecord["type"], currency: input.currency, initialBalance: fromMinorUnit(input.initialBalance), balance: fromMinorUnit(input.initialBalance), isActive: true, color: "#5b6ee1", symbol: input.name.slice(0, 1) }; const next = accountId ? accounts.map((item) => item.id === accountId ? record : item) : [record, ...accounts]; write("accounts", next); return record;
}
export async function setAccountActive(accountId: string, active: boolean): Promise<void> { if (isTauri()) { await invoke("set_account_active", { id: accountId, active }); return; } write("accounts", read<AccountRecord[]>("accounts", []).map((a) => a.id === accountId ? { ...a, isActive: active } : a)); }
export async function deleteAccount(accountId: string): Promise<void> { if (isTauri()) { await invoke("delete_account", { id: accountId }); return; } write("accounts", read<AccountRecord[]>("accounts", []).filter((a) => a.id !== accountId)); }

export async function getCategories(type?: "INCOME" | "EXPENSE"): Promise<CategoryRecord[]> { if (isTauri()) return invoke<CategoryRecord[]>("get_categories", { kind: type }); return read<CategoryRecord[]>("categories", []).filter((c) => !type || c.type === type); }
export async function saveCategory(input: Omit<CategoryRecord, "id">, categoryId?: string): Promise<CategoryRecord> { if (isTauri()) return invoke<CategoryRecord>("save_category", { input, idOpt: categoryId }); const rows = read<CategoryRecord[]>("categories", []); const record = { ...input, id: categoryId ?? id() }; write("categories", categoryId ? rows.map((r) => r.id === categoryId ? record : r) : [...rows, record]); return record; }
export async function setCategoryActive(categoryId: string, active: boolean): Promise<void> { if (isTauri()) { await invoke("set_category_active", { id: categoryId, active }); return; } write("categories", read<CategoryRecord[]>("categories", []).map((c) => c.id === categoryId ? { ...c, isActive: active } : c)); }
export async function getTransactions(): Promise<TransactionRecord[]> { if (isTauri()) return (await invoke<TransactionDto[]>("get_transactions", { from: null, to: null })).map(mapTransaction); return read<TransactionRecord[]>("transactions", []); }
export async function getTransactionPage(offset: number, limit: number): Promise<TransactionRecord[]> { if (isTauri()) return (await invoke<TransactionDto[]>("get_transactions_page", { offset, limit })).map(mapTransaction); return read<TransactionRecord[]>("transactions", []).slice(offset, offset + limit); }
export async function saveTransaction(input: { type: "INCOME" | "EXPENSE" | "ADJUSTMENT"; accountId: string; categoryId?: string; amount: number; currency: string; merchant: string; transactionDate: number; note: string }, transactionId?: string): Promise<TransactionRecord> { if (isTauri()) return mapTransaction(await invoke<TransactionDto>("save_transaction", { input, idOpt: transactionId })); const accounts = await getAccounts(); const category = (await getCategories()).find((c) => c.id === input.categoryId); const record: TransactionRecord = { id: transactionId ?? id(), title: input.merchant || category?.name || "交易", account: accounts.find((a) => a.id === input.accountId)?.name ?? "账户", category: category?.name ?? "未分类", amount: fromMinorUnit(input.amount), type: input.type === "INCOME" ? "income" : input.type === "EXPENSE" ? "expense" : "adjustment", timestamp: new Date(input.transactionDate).toLocaleString("zh-CN"), icon: "•", accountId: input.accountId, categoryId: input.categoryId, currency: input.currency, merchant: input.merchant, note: input.note, transactionDate: input.transactionDate }; const txs = read<TransactionRecord[]>("transactions", []); write("transactions", transactionId ? txs.map((t) => t.id === transactionId ? record : t) : [record, ...txs]); const delta = input.type === "INCOME" ? input.amount : input.type === "EXPENSE" ? -input.amount : input.amount; write("accounts", accounts.map((a) => a.id === input.accountId ? { ...a, balance: a.balance + fromMinorUnit(delta) } : a)); return record; }
export async function deleteTransaction(transactionId: string): Promise<void> { if (isTauri()) { await invoke("delete_transaction", { id: transactionId }); return; } write("transactions", read<TransactionRecord[]>("transactions", []).filter((t) => t.id !== transactionId)); }
export interface TransferRecord { id: string; fromAccountId: string; fromAccountName: string; toAccountId: string; toAccountName: string; amount: number; currency: string; transferDate: number; note: string }
export async function createTransfer(input:{fromAccountId:string;toAccountId:string;amount:number;currency:string;transferDate:number;note:string}):Promise<void>{if(isTauri()){await invoke("create_transfer",input);return;}throw new Error("转账需要在桌面应用中执行");}
export async function getTransfers():Promise<TransferRecord[]>{if(isTauri()){const rows=await invoke<TransferRecord[]>("get_transfers");return rows.map((row)=>({...row,amount:fromMinorUnit(row.amount)}));}return read("transfers",[]);}
export async function deleteTransfer(recordId:string):Promise<void>{if(isTauri()){await invoke("delete_transfer",{id:recordId});return;}write("transfers",read<TransferRecord[]>("transfers",[]).filter((row)=>row.id!==recordId));}
export async function getDashboard(): Promise<DashboardData> { if (isTauri()) { const row=await invoke<{totalBalance:number;monthlyIncome:number;monthlyExpenses:number;monthlySavings:number;accountCount:number;accounts:AccountDto[];transactions:TransactionDto[];balancesByCurrency:Array<{currency:string;amount:number}>;balanceTrend:Array<{label:string;balance:number}>}>("get_dashboard"); return {...row,totalBalance:fromMinorUnit(row.totalBalance),monthlyIncome:fromMinorUnit(row.monthlyIncome),monthlyExpenses:fromMinorUnit(row.monthlyExpenses),monthlySavings:fromMinorUnit(row.monthlySavings),accounts:row.accounts.map(mapAccount),transactions:row.transactions.map(mapTransaction),balancesByCurrency:row.balancesByCurrency.map((value)=>({...value,amount:fromMinorUnit(value.amount)})),balanceTrend:row.balanceTrend.map((value)=>({...value,balance:fromMinorUnit(value.balance)}))}; } const [accounts, transactions] = await Promise.all([getAccounts(), getTransactions()]); const month = new Date(); const income = transactions.filter((t) => t.currency === "CNY" && t.type === "income" && new Date(t.transactionDate).getFullYear() === month.getFullYear() && new Date(t.transactionDate).getMonth() === month.getMonth()).reduce((s, t) => s + t.amount, 0); const expense = transactions.filter((t) => t.currency === "CNY" && t.type === "expense" && new Date(t.transactionDate).getFullYear() === month.getFullYear() && new Date(t.transactionDate).getMonth() === month.getMonth()).reduce((s, t) => s + t.amount, 0); const active=accounts.filter((a)=>a.isActive); const totals=active.reduce<Record<string,number>>((values,account)=>({...values,[account.currency]:(values[account.currency]??0)+account.balance}),{}); return { totalBalance: totals.CNY??0, monthlyIncome: income, monthlyExpenses: expense, monthlySavings: income - expense, accountCount: active.length, accounts, transactions: transactions.slice(0, 8), balancesByCurrency:Object.entries(totals).map(([currency,amount])=>({currency,amount})),balanceTrend:[] }; }
export const localDateInput = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
export async function getSimpleRecords(kind: "planned" | "installments" | "budgets"): Promise<Array<{ id: string; title: string; amount: number; date: number; status: string }>> { if (isTauri()) return invoke("get_simple_records", { kind }); return read(kind, []); }
export async function getSetting(name: string): Promise<string | null> { if (isTauri()) return invoke<string | null>("get_setting", { key: name }); return read<Record<string, string>>("settings", {})[name] ?? null; }
export async function setSetting(name: string, value: string): Promise<void> { if (isTauri()) { await invoke("set_setting", { key: name, value }); return; } write("settings", { ...read<Record<string, string>>("settings", {}), [name]: value }); }
export async function searchAll(query: string): Promise<string[]> { if (!query.trim()) return []; if (isTauri()) return invoke<string[]>("search_all", { query }); const q = query.toLowerCase(); const [accounts, tx] = await Promise.all([getAccounts(), getTransactions()]); return [...accounts.filter((a) => a.name.toLowerCase().includes(q)).map((a) => `账户 · ${a.name}`), ...tx.filter((t) => `${t.title}${t.note}`.toLowerCase().includes(q)).map((t) => `交易 · ${t.title}`)].slice(0, 30); }
export interface RecurringRecord { id: string; type: string; accountId: string; categoryId?: string; amount: number; currency: string; title: string; frequency: string; startDate: number; endDate?: number; nextRunDate: number; isActive: boolean; note?: string; lastTransactionId?: string; }
export interface PlannedRecord { id: string; title: string; amount: number; currency: string; plannedDate: number; categoryId?: string; accountId: string; status: string; note: string; transactionId?: string; }
export interface InstallmentRecord { id: string; title: string; totalAmount: number; installmentCount: number; installmentAmount: number; firstPaymentDate: number; paidCount: number; remainingCount: number; remainingAmount: number; accountId: string; status: string; note?: string; lastTransactionId?: string; }
export interface BudgetRecord { id: string; categoryId: string; categoryName: string; amount: number; spent: number; currency: string; year: number; month: number; }
export async function getRecurring(): Promise<RecurringRecord[]> { if (isTauri()) return invoke("get_recurring"); return read("recurring", []); }
export async function saveRecurring(input: Omit<RecurringRecord, "id" | "nextRunDate" | "isActive">, recordId?: string): Promise<void> { if (isTauri()) { await invoke("save_recurring", { input: { ...input, amount: input.amount }, idOpt: recordId }); return; } write("recurring", [...read<RecurringRecord[]>("recurring", []), { ...input, id: recordId ?? id(), nextRunDate: input.startDate, isActive: true }]); }
export async function setRecurringActive(recordId: string, active: boolean): Promise<void> { if (isTauri()) { await invoke("set_recurring_active", { id: recordId, active }); return; } write("recurring", read<RecurringRecord[]>("recurring", []).map((r) => r.id === recordId ? { ...r, isActive: active } : r)); }
export async function deleteRecurring(recordId: string): Promise<void> { if (isTauri()) { await invoke("delete_recurring", { id: recordId }); return; } write("recurring", read<RecurringRecord[]>("recurring", []).filter((r) => r.id !== recordId)); }
export async function postRecurring(recordId:string):Promise<string>{if(isTauri())return invoke<string>("post_recurring",{recurringId:recordId});throw new Error("固定收支入账需要在桌面应用中执行");}
export async function undoRecurringPayment(recordId:string):Promise<void>{if(isTauri()){await invoke("undo_recurring_payment",{recurringId:recordId});return;}throw new Error("撤销入账需要在桌面应用中执行");}
export async function getPlanned(): Promise<PlannedRecord[]> { if (isTauri()) return invoke<PlannedRecord[]>("get_planned"); return read("planned", []); }
export async function savePlanned(input: Omit<PlannedRecord, "id" | "status">, recordId?: string): Promise<void> { if (isTauri()) { await invoke("save_planned", { input, idOpt: recordId }); return; } write("planned", [...read<PlannedRecord[]>("planned", []), { ...input, id: recordId ?? id(), status: "PLANNED" }]); }
export async function completePlanned(recordId: string): Promise<void> { if (isTauri()) { await invoke("complete_planned", { plannedId: recordId }); return; } }
export async function undoPlanned(recordId:string):Promise<void>{if(isTauri()){await invoke("undo_planned",{id:recordId});return;}throw new Error("撤销入账需要在桌面应用中执行");}
export async function cancelPlanned(recordId: string): Promise<void> { if (isTauri()) { await invoke("cancel_planned", { id: recordId }); return; } write("planned", read<PlannedRecord[]>("planned", []).map((r) => r.id === recordId ? { ...r, status: "CANCELLED" } : r)); }
export async function deletePlanned(recordId: string): Promise<void> { if (isTauri()) { await invoke("delete_planned", { id: recordId }); return; } write("planned", read<PlannedRecord[]>("planned", []).filter((r) => r.id !== recordId)); }
export async function getInstallments(): Promise<InstallmentRecord[]> { if (isTauri()) return invoke("get_installments"); return read("installments", []); }
export async function saveInstallment(input: Omit<InstallmentRecord, "id" | "installmentAmount" | "paidCount" | "remainingCount" | "remainingAmount" | "status">, recordId?: string): Promise<void> { if (isTauri()) { await invoke("save_installment", { input, idOpt: recordId }); return; } const each = Math.floor(input.totalAmount / input.installmentCount); write("installments", [...read<InstallmentRecord[]>("installments", []), { ...input, id: recordId ?? id(), installmentAmount: each, paidCount: 0, remainingCount: input.installmentCount, remainingAmount: input.totalAmount, status: "ACTIVE" }]); }
export async function payInstallment(recordId: string): Promise<void> { if (isTauri()) { await invoke("pay_installment", { installmentId: recordId }); return; } }
export async function undoInstallmentPayment(recordId:string):Promise<void>{if(isTauri()){await invoke("undo_installment_payment",{installmentId:recordId});return;}throw new Error("撤销付款需要在桌面应用中执行");}
export async function deleteInstallment(recordId: string): Promise<void> { if (isTauri()) { await invoke("delete_installment", { id: recordId }); return; } write("installments", read<InstallmentRecord[]>("installments", []).filter((r) => r.id !== recordId)); }
export async function cancelInstallment(recordId: string): Promise<void> { if (isTauri()) { await invoke("cancel_installment", { id: recordId }); return; } write("installments", read<InstallmentRecord[]>("installments", []).map((r) => r.id === recordId ? { ...r, status: "CANCELLED" } : r)); }
export async function getBudgets(year: number, month: number): Promise<BudgetRecord[]> { if (isTauri()) return invoke("get_budgets", { year, month }); return read<BudgetRecord[]>("budgets", []).filter((b) => b.year === year && b.month === month); }
export async function saveBudget(input: Omit<BudgetRecord, "id" | "categoryName" | "spent">, recordId?: string): Promise<void> { if (isTauri()) { await invoke("save_budget", { input, idOpt: recordId }); return; } write("budgets", [...read<BudgetRecord[]>("budgets", []), { ...input, id: recordId ?? id(), categoryName: "分类", spent: 0 }]); }
export async function deleteBudget(recordId: string): Promise<void> { if (isTauri()) { await invoke("delete_budget", { id: recordId }); return; } write("budgets", read<BudgetRecord[]>("budgets", []).filter((r) => r.id !== recordId)); }
export interface ForecastRecord { date: number; balance: number; income: number; expense: number; label: string; }
export interface PurchaseResult { verdict: "OK" | "CAUTION" | "NOT_RECOMMENDED"; currentBalance: number; balanceAfterPurchase: number; minimumFutureBalance: number; safetyBalance: number; reason: string; }
export async function getForecast(days: number): Promise<ForecastRecord[]> { if (isTauri()) { const rows = await invoke<ForecastRecord[]>("get_forecast", { days }); return rows.map((r) => ({ ...r, balance: fromMinorUnit(r.balance), income: fromMinorUnit(r.income), expense: fromMinorUnit(r.expense) })); } const d = await getDashboard(); return Array.from({ length: days + 1 }, (_, i) => ({ date: Date.now() + i * 86_400_000, balance: d.totalBalance, income: 0, expense: 0, label: `+${i}d` })); }
export async function canBuy(amount: number, purchaseDate: number): Promise<PurchaseResult> { if (isTauri()) { const r = await invoke<PurchaseResult>("can_buy", { amount, purchaseDate }); return { ...r, currentBalance: fromMinorUnit(r.currentBalance), balanceAfterPurchase: fromMinorUnit(r.balanceAfterPurchase), minimumFutureBalance: fromMinorUnit(r.minimumFutureBalance), safetyBalance: fromMinorUnit(r.safetyBalance) }; } const d = await getDashboard(); const safety = Number(await getSetting("safety_balance") ?? toMinorUnit("10000")) / 100; const after = d.totalBalance - fromMinorUnit(amount); return { verdict: after < safety ? "NOT_RECOMMENDED" : after < safety * 2 ? "CAUTION" : "OK", currentBalance: d.totalBalance, balanceAfterPurchase: after, minimumFutureBalance: after, safetyBalance: safety, reason: after < safety ? "购买后余额低于安全余额" : "预计现金流能够覆盖这笔购买" }; }
export async function exportFinanceJson(): Promise<string> { const [accounts, transactions, categories] = await Promise.all([getAccounts(), getTransactions(), getCategories()]); return JSON.stringify({ exportedAt: new Date().toISOString(), accounts, transactions, categories }, null, 2); }
export async function exportTransactionsCsv(): Promise<string> { const rows = await getTransactions(); return ["id,type,account,category,amount,currency,date,merchant,note", ...rows.map((r) => [r.id, r.type, r.account, r.category, r.amount.toFixed(2), r.currency, new Date(r.transactionDate).toISOString(), r.merchant, r.note].map((v) => `"${v.replaceAll('"', '""')}"`).join(","))].join("\n"); }
function databaseError(reason: unknown): Error {
  return reason instanceof Error ? reason : new Error(typeof reason === "string" ? reason : "数据库操作失败，请重试");
}
export async function backupDatabase(destination: string): Promise<void> {
  if (!isTauri()) throw new Error("SQLite 备份需要在桌面应用中执行");
  try { await flushAllNotes(); await invoke("backup_database", { destination }); }
  catch (reason) { throw databaseError(reason); }
}
export async function restoreDatabase(source: string): Promise<void> {
  if (!isTauri()) throw new Error("SQLite 恢复需要在桌面应用中执行");
  try { await flushAllNotes(); await invoke("restore_database", { source }); }
  catch (reason) { throw databaseError(reason); }
  window.sessionStorage.setItem("my-personal-affairs:login-notice", "数据库已恢复，请使用备份时的密码重新登录；不含安全配置的旧备份会进入首次设置流程。");
  await useAuthStore.getState().logout();
  window.dispatchEvent(new Event("finance-data-changed"));
}
export interface FileInfo { name: string; size: number; modified: number }
export async function getFileInfo(path: string): Promise<FileInfo> { if (isTauri()) return invoke<FileInfo>("get_file_info", { path }); throw new Error("文件信息需要在桌面应用中读取"); }
