import { Pencil, Plus, Power, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { AccountCard } from "@/components/dashboard/account-card";
import { PageHero } from "@/components/page-hero";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { deleteAccount, getAccounts, saveAccount, setAccountActive, toMinorUnit, fromMinorUnit } from "@/services/finance-service";
import type { AccountRecord } from "@/types/finance";

export function AccountsPage() {
  const [accounts, setAccounts] = useState<AccountRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AccountRecord | null>(null);
  const load = () => { setLoading(true); void getAccounts().then(setAccounts).catch((e: unknown) => setError(e instanceof Error ? e.message : "加载账户失败")).finally(() => setLoading(false)); }; useEffect(load, []);
  return (
    <div className="page-container"><PageHero title="账户" description="一目了然地查看所有资金所在。" action={<Button onClick={() => { setEditing(null); setOpen(true); }}><Plus className="size-4" />添加账户</Button>} />
      {loading ? <div className="content-card p-8 text-sm text-[var(--text-secondary)]">正在加载账户…</div> : error ? <div className="content-card flex items-center justify-between p-8 text-sm text-[var(--danger)]">{error}<Button variant="secondary" onClick={load}>重试</Button></div> : accounts.length === 0 ? <div className="content-card p-8 text-center text-sm text-[var(--text-secondary)]">还没有账户，添加你的第一个账户。</div> : <div className="account-grid">{accounts.map((account) => <div key={account.id} className="relative"><AccountCard account={account} /><div className="absolute right-3 top-3 flex gap-1"><button aria-label="编辑账户" className="rounded-lg p-1.5 text-[var(--text-tertiary)] hover:bg-[var(--surface-muted)]" onClick={() => { setEditing(account); setOpen(true); }}><Pencil className="size-4" /></button><button aria-label={account.isActive ? "停用账户" : "启用账户"} className="rounded-lg p-1.5 text-[var(--text-tertiary)] hover:bg-[var(--surface-muted)]" onClick={() => void setAccountActive(account.id, !account.isActive).then(load)}><Power className="size-4" /></button><button aria-label="删除账户" className="rounded-lg p-1.5 text-[var(--danger)] hover:bg-[var(--danger-soft)]" onClick={() => { if (window.confirm("没有交易记录的账户才可以删除，确定继续吗？")) void deleteAccount(account.id).then(load).catch((e: unknown) => setError(e instanceof Error ? e.message : "删除失败")); }}><Trash2 className="size-4" /></button></div></div>)}</div>}
      <AccountDialog open={open} onOpenChange={setOpen} account={editing} onSaved={() => { setOpen(false); load(); }} />
    </div>
  );
}

function AccountDialog({ open, onOpenChange, account, onSaved }: { open: boolean; onOpenChange: (open: boolean) => void; account: AccountRecord | null; onSaved: () => void }) { const [name, setName] = useState(""); const [institution, setInstitution] = useState(""); const [type, setType] = useState("银行卡"); const [currency, setCurrency] = useState("CNY"); const [balance, setBalance] = useState(""); const [error, setError] = useState<string | null>(null); useEffect(() => { setName(account?.name ?? ""); setInstitution(account?.institution ?? ""); setType(account?.type ?? "银行卡"); setCurrency(account?.currency ?? "CNY"); setBalance(account ? String(fromMinorUnit(account.initialBalance)) : ""); setError(null); }, [account, open]); return <Dialog open={open} onOpenChange={onOpenChange} title={account ? "编辑账户" : "添加账户"} description="余额以最小货币单位安全保存。"><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); setError(null); if (!name.trim()) { setError("账户名称不能为空"); return; } void saveAccount({ name, institution, type, currency, initialBalance: toMinorUnit(balance) }, account?.id).then(onSaved).catch((e: unknown) => setError(e instanceof Error ? e.message : "保存失败")); }}><label className="form-label">账户名称<input className="form-control" value={name} onChange={(e) => setName(e.target.value)} placeholder="例如：招商银行" /></label><label className="form-label">银行 / 平台<input className="form-control" value={institution} onChange={(e) => setInstitution(e.target.value)} placeholder="例如：储蓄卡" /></label><div className="grid grid-cols-2 gap-3"><label className="form-label">账户类型<select className="form-control" value={type} onChange={(e) => setType(e.target.value)}><option>银行卡</option><option>电子钱包</option><option>现金</option><option>信用卡</option><option>投资</option><option>其他</option></select></label><label className="form-label">货币<select className="form-control" value={currency} onChange={(e) => setCurrency(e.target.value)}><option value="CNY">CNY 人民币</option><option value="USD">USD 美元</option><option value="JPY">JPY 日元</option></select></label></div><label className="form-label">初始余额<input className="form-control" inputMode="decimal" value={balance} onChange={(e) => setBalance(e.target.value)} placeholder="0.00" /></label>{error && <p className="text-sm text-[var(--danger)]">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => onOpenChange(false)}>取消</Button><Button type="submit">保存账户</Button></div></form></Dialog> }
