import { CreditCard, Pencil, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { EmptyState } from "@/components/empty-state";
import { PageHero } from "@/components/page-hero";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { cancelInstallment, deleteInstallment, getAccounts, getInstallments, payInstallment, saveInstallment, toMinorUnit, type InstallmentRecord } from "@/services/finance-service";
import { formatCurrency } from "@/lib/utils";
import type { AccountRecord } from "@/types/finance";
export function InstallmentsPage(){const [rows,setRows]=useState<InstallmentRecord[]>([]);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<InstallmentRecord|null>(null);const [error,setError]=useState<string|null>(null);const [loading,setLoading]=useState(true);const load=()=>{setLoading(true);void getInstallments().then(setRows).catch((e:unknown)=>setError(e instanceof Error?e.message:"加载失败")).finally(()=>setLoading(false));};useEffect(()=>{load();window.addEventListener("finance-data-changed",load);return()=>window.removeEventListener("finance-data-changed",load);},[]);return <div className="page-container"><PageHero title="分期" description="将长期付款拆分为清晰、可追踪的每一期。" action={<Button onClick={()=>{setEditing(null);setOpen(true);}}><Plus className="size-4"/>添加分期</Button>}/>{loading?<div className="content-card p-6 text-[var(--text-secondary)]">正在加载分期…</div>:error?<div className="content-card p-6 text-[var(--danger)]">{error}<Button variant="secondary" className="ml-4" onClick={load}>重试</Button></div>:rows.length?<div className="content-card divide-y divide-[var(--border)]">{rows.map(r=><div className="py-4" key={r.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium text-[var(--text)]">{r.title}</p><p className="mt-1 text-xs text-[var(--text-secondary)]">总额 {formatCurrency(r.totalAmount/100)} · 每期 {formatCurrency(r.installmentAmount/100)} · 首期 {new Date(r.firstPaymentDate).toLocaleDateString("zh-CN")}</p></div><div className="flex items-center gap-2"><Button size="sm" disabled={r.status!=="ACTIVE"} onClick={()=>void payInstallment(r.id).then(()=>{window.dispatchEvent(new Event("finance-data-changed"));load();})}>标记已付</Button><button aria-label="编辑分期" onClick={()=>{setEditing(r);setOpen(true);}}><Pencil className="size-4"/></button><button aria-label="取消分期" onClick={()=>{if(window.confirm("取消后不会再产生付款，继续吗？"))void cancelInstallment(r.id).then(load);}}><span className="text-xs text-[var(--warning)]">取消</span></button><button aria-label="删除分期" onClick={()=>{if(window.confirm(r.paidCount?"已付款分期不能删除，可保留历史记录。":"删除此分期？"))void deleteInstallment(r.id).then(load);}}><Trash2 className="size-4 text-[var(--danger)]"/></button></div></div><div className="mt-3 flex gap-6 text-sm text-[var(--text-secondary)]"><span>已支付 {formatCurrency((r.totalAmount-r.remainingAmount)/100)}</span><span>剩余 {formatCurrency(r.remainingAmount/100)}</span><span>进度 {r.paidCount}/{r.installmentCount}</span><span>下一期 {r.status==="ACTIVE"?new Date(r.firstPaymentDate+r.paidCount*30*86400000).toLocaleDateString("zh-CN"):"-"}</span></div></div>)}</div>:<EmptyState icon={CreditCard} title="还没有进行中的分期" description="添加分期计划后，每一期付款都会生成实际支出。"/>}<InstallmentDialog open={open} record={editing} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load();window.dispatchEvent(new Event("finance-data-changed"));}}/></div>}
function InstallmentDialog({open,record,onClose,onSaved}:{open:boolean;record:InstallmentRecord|null;onClose:()=>void;onSaved:()=>void}){const [accounts,setAccounts]=useState<AccountRecord[]>([]);const [error,setError]=useState<string|null>(null);useEffect(()=>{void getAccounts().then(setAccounts);},[]);return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}} title={record?"编辑分期":"添加分期"} description="已付款分期只允许修改未来计划字段。"><form className="space-y-3" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void saveInstallment({title:String(d.get("title")),totalAmount:toMinorUnit(String(d.get("total"))),installmentCount:Number(d.get("count")),firstPaymentDate:new Date(String(d.get("date"))).getTime(),accountId:String(d.get("accountId")),note:String(d.get("note")??"")},record?.id).then(onSaved).catch((x:unknown)=>setError(x instanceof Error?x.message:"保存失败"));}}><label className="form-label">名称<input name="title" required defaultValue={record?.title??""} className="form-control"/></label><div className="grid grid-cols-2 gap-3"><label className="form-label">总金额<input name="total" required defaultValue={record?record.totalAmount/100:""} className="form-control" inputMode="decimal"/></label><label className="form-label">期数<input name="count" required min="1" type="number" defaultValue={record?.installmentCount??3} className="form-control"/></label></div><label className="form-label">账户<select name="accountId" required defaultValue={record?.accountId??accounts[0]?.id} className="form-control">{accounts.filter(a=>a.isActive).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="form-label">首次付款日期<input name="date" required type="date" defaultValue={record?new Date(record.firstPaymentDate).toISOString().slice(0,10):new Date().toISOString().slice(0,10)} className="form-control"/></label><label className="form-label">备注<textarea name="note" defaultValue={record?.note??""} className="form-control" rows={2}/></label>{error&&<p className="text-sm text-[var(--danger)]">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>取消</Button><Button type="submit">保存</Button></div></form></Dialog>}
