import { CreditCard, Pencil, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { EmptyState } from "@/components/empty-state";
import { PageHero } from "@/components/page-hero";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { cancelInstallment, deleteInstallment, getAccounts, getInstallments, localDateInput, payInstallment, saveInstallment, toMinorUnit, undoInstallmentPayment, type InstallmentRecord } from "@/services/finance-service";
import { formatCurrency } from "@/lib/utils";
import type { AccountRecord } from "@/types/finance";

const installmentDate=(first:number,paid:number)=>{const date=new Date(first);const day=date.getDate();date.setDate(1);date.setMonth(date.getMonth()+paid);date.setDate(Math.min(day,new Date(date.getFullYear(),date.getMonth()+1,0).getDate()));return date;};
export function InstallmentsPage(){
  const [rows,setRows]=useState<InstallmentRecord[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<InstallmentRecord|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);
  const load=()=>{setLoading(true);void getInstallments().then((values)=>{setRows(values);setError(null);}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:"加载失败")).finally(()=>setLoading(false));};
  useEffect(()=>{load();window.addEventListener("finance-data-changed",load);return()=>window.removeEventListener("finance-data-changed",load);},[]);
  const act=(work:Promise<unknown>)=>void work.then(()=>{load();window.dispatchEvent(new Event("finance-data-changed"));}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:"操作失败"));
  return <div className="page-container"><PageHero title="分期" description="每一期付款都会关联实际交易，可撤销最近一期。" action={<Button onClick={()=>{setEditing(null);setOpen(true);}}><Plus className="size-4"/>添加分期</Button>}/>{loading?<div className="content-card p-6">正在加载分期…</div>:error?<div className="content-card p-6 text-[var(--danger)]">{error}<Button variant="secondary" className="ml-4" onClick={load}>重试</Button></div>:rows.length?<div className="content-card divide-y divide-[var(--border)]">{rows.map((row)=><div className="py-4" key={row.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{row.title}</p><p className="mt-1 text-xs text-[var(--text-secondary)]">总额 {formatCurrency(row.totalAmount/100)} · 每期 {formatCurrency(row.installmentAmount/100)} · 首期 {new Date(row.firstPaymentDate).toLocaleDateString("zh-CN")}</p></div><div className="flex items-center gap-2"><Button size="sm" disabled={row.status!=="ACTIVE"} onClick={()=>act(payInstallment(row.id))}>本期付款</Button>{row.lastTransactionId&&<Button size="sm" variant="secondary" onClick={()=>{if(confirm("撤销最近一期付款及其实际支出？"))act(undoInstallmentPayment(row.id));}}>撤销最近</Button>}<button disabled={row.paidCount>0} aria-label="编辑分期" title={row.paidCount>0?"已有付款的分期不能修改总额和期数":"编辑分期"} onClick={()=>{setEditing(row);setOpen(true);}}><Pencil className="size-4"/></button><button aria-label="取消分期" onClick={()=>{if(confirm("取消后不会再产生付款，继续吗？"))act(cancelInstallment(row.id));}}><span className="text-xs text-[var(--warning)]">取消</span></button><button aria-label="删除分期" onClick={()=>{if(confirm(row.paidCount?"已有付款的分期不能删除。":"删除此分期？"))act(deleteInstallment(row.id));}}><Trash2 className="size-4 text-[var(--danger)]"/></button></div></div><div className="mt-3 flex flex-wrap gap-6 text-sm text-[var(--text-secondary)]"><span>已支付 {formatCurrency((row.totalAmount-row.remainingAmount)/100)}</span><span>剩余 {formatCurrency(row.remainingAmount/100)}</span><span>进度 {row.paidCount}/{row.installmentCount}</span><span>下一期 {row.status==="ACTIVE"?installmentDate(row.firstPaymentDate,row.paidCount).toLocaleDateString("zh-CN"):"-"}</span></div></div>)}</div>:<EmptyState icon={CreditCard} title="还没有分期" description="添加分期计划后，每一期付款都会生成实际支出。"/>}<InstallmentDialog open={open} record={editing} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load();window.dispatchEvent(new Event("finance-data-changed"));}}/></div>;
}
function InstallmentDialog({open,record,onClose,onSaved}:{open:boolean;record:InstallmentRecord|null;onClose:()=>void;onSaved:()=>void}){const [accounts,setAccounts]=useState<AccountRecord[]>([]),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);useEffect(()=>{if(open)void getAccounts().then(setAccounts);},[open]);return <Dialog open={open} onOpenChange={(value)=>{if(!value&&!busy)onClose();}} title={record?"编辑分期":"添加分期"} description="已付款后总额和期数将锁定；需要变更时先撤销付款。"><form className="space-y-3" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);void saveInstallment({title:String(data.get("title")),totalAmount:toMinorUnit(String(data.get("total"))),installmentCount:Number(data.get("count")),firstPaymentDate:new Date(`${String(data.get("date"))}T12:00:00`).getTime(),accountId:String(data.get("accountId")),note:String(data.get("note")??"")},record?.id).then(onSaved).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:"保存失败")).finally(()=>setBusy(false));}}><label className="form-label">名称<input name="title" required defaultValue={record?.title??""} className="form-control"/></label><div className="grid grid-cols-2 gap-3"><label className="form-label">总金额<input name="total" required defaultValue={record?record.totalAmount/100:""} className="form-control" inputMode="decimal"/></label><label className="form-label">期数<input name="count" required min="1" type="number" defaultValue={record?.installmentCount??3} className="form-control"/></label></div><label className="form-label">账户<select name="accountId" required defaultValue={record?.accountId??accounts[0]?.id} className="form-control">{accounts.filter((account)=>account.isActive).map((account)=><option key={account.id} value={account.id}>{account.name} · {account.currency}</option>)}</select></label><label className="form-label">首次付款日期<input name="date" required type="date" defaultValue={record?localDateInput(new Date(record.firstPaymentDate)):localDateInput()} className="form-control"/></label><label className="form-label">备注<textarea name="note" defaultValue={record?.note??""} className="form-control" rows={2}/></label>{error&&<p className="text-sm text-[var(--danger)]">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>取消</Button><Button type="submit" disabled={busy}>{busy?"保存中…":"保存"}</Button></div></form></Dialog>}
